name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0

      - name: Set environment variable CI=false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Install dependencies and build
        run: |
          cd ./    # Change directory to the source directory
          npm install
          npm run build

      - name: Run HTML file
        run: |
          cd ./build    # Change directory to the build directory
          python -m http.server 8080
